FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY tsconfig.json ./
COPY apps/webhook-server/package*.json ./apps/webhook-server/
COPY apps/agent-worker/package*.json ./apps/agent-worker/
COPY packages/shared/package*.json ./packages/shared/

RUN npm install

COPY . .

RUN npm run prisma:generate

EXPOSE 3001
EXPOSE 3002

CMD ["npm", "run", "dev:webhook"]
